# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: kubesource

builds:
  - main: ./cmd/kubesource
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}}
      - -extldflags "-static"

checksum:
  name_template: "checksums.txt"

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- tolower .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

snapshot:
  version_template: "{{ incpatch .Version }}-next"
